/* SPDX-License-Identifier: Apache-2.0 */
/* Copyright © 2019-2022 Tensil AI Company */

#pragma once

#define TENSIL_PLATFORM_DECODER_TIMEOUT 100

#define TENSIL_PLATFORM_ENABLE_FILE_SYSTEM
#define TENSIL_PLATFORM_ENABLE_STDIO

#define TENSIL_PLATFORM_INSTRUCTION_AXI_DMA_DEVICE_ID XPAR_AXIDMA_0_DEVICE_ID

#define TENSIL_PLATFORM_PROG_BUFFER_BASE 0x10000000
#define TENSIL_PLATFORM_PROG_BUFFER_HIGH 0x40000000

#define TENSIL_PLATFORM_DRAM_BUFFER_BASE TENSIL_PLATFORM_PROG_BUFFER_HIGH
#define TENSIL_PLATFORM_DRAM_BUFFER_HIGH 0x50000000